import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {execFileSync} from "node:child_process";

const root=new URL("../",import.meta.url);
const read=file=>readFileSync(new URL(file,root),"utf8");
const main=read("js/main.js"),rules=read("firestore.rules"),storage=read("storage.rules"),html=read("index.html"),config=read("js/firebase-config.js");
const firebase=JSON.parse(read("firebase.json")),manifest=JSON.parse(read("manifest.json"));

execFileSync(process.execPath,["--check",decodeURIComponent(new URL("js/main.js",root).pathname)],{stdio:"pipe"});
execFileSync(process.execPath,["--check",decodeURIComponent(new URL("js/pdf-generator.js",root).pathname)],{stdio:"pipe"});
assert.equal(manifest.version,"23.0.0");
assert.equal(firebase.firestore.rules,"firestore.rules");
assert.ok(html.includes("23.0.0"));
assert.ok(!config.includes("team-f78cd"),"A V23 não pode apontar para o Firebase antigo");
assert.ok(config.includes('projectId: "SEU-NOVO-PROJETO"'));
assert.ok(main.includes('const batch=writeBatch(db);'));
assert.ok(main.includes('batch.update(doc(db,"users",u.id)'));
assert.ok(main.includes('batch.set(doc(db,"members",u.id)'));
assert.ok(main.includes('batch.set(doc(db,"nicknameClaims",key)'));
assert.ok(!main.includes("Firestore negou a aprovação. Perfil atual:"));
assert.ok(rules.includes("function staffCanUpdateUser()"));
assert.ok(rules.includes("staff() && pendingMember(resource.data)"));
assert.ok(rules.includes("allow create, update: if editor() ||"));
assert.ok(rules.includes("match /members/{id}"));
assert.ok(rules.includes("match /nicknameClaims/{key}"));
assert.ok(rules.includes("match /public/{docId}"));
assert.ok(rules.includes("match /attendance/{id}"));
assert.ok(rules.includes("match /events/{id}"));
assert.ok(rules.includes("match /supportMessages/{id}"));
assert.ok(rules.includes("match /chatMessages/{id}"));
assert.ok(storage.includes("function editor()"));
assert.ok(main.includes('accessRole:"member",memberRole:"Membros"'));
assert.ok(main.includes('status:"pending"'));
assert.ok(main.includes('profileStatus==="pending"?"Conta ainda não aprovada."'));
assert.ok(html.includes('id="publicHomeBanner"'));
console.log("Auditoria estática V23.0.0: OK");
